- name: test_prep calisiyor
  hosts: all
  become: True
  #remote_user: menek
  gather_facts: yes
  vars:
    - user: vio
      #- password: menek
    - k8s_version: "1.22"                                  # Kubernetes version to be installed
    - selinux_state: permissive                            # SELinux state to be set on k8s nodes 
    - timezone: "Africa/Nairobi"                           # Timezone to set on all nodes
    - k8s_cni: calico                                      # calico, flannel
    - container_runtime: docker                             # docker, cri-o, containerd 
    - pod_network_cidr: "172.16.0.0/16"                   # pod subnet if using cri-o runtime
    - configure_firewalld: false                           # true / false (keep it false, k8s>1.19 have issues with firewalld)
    # Docker proxy support
    - setup_proxy: false                                   # Set to true to configure proxy
    - proxy_server: "proxy.example.com:8080"               # Proxy server address and port
    - docker_proxy_exclude: "localhost,127.0.0.1"          # Adresses to exclude from proxy  
  vars_prompt:
    - name: "user_password"
      prompt: "Enter password for the user {{ user }}"
      encrypt: "md5_crypt" #need to have python-passlib installed in local machine before we can use it
      confirm: yes
      salt_size: 7
    - name: "ssh_passphrase"
      prompt: "Enter the passphrase for the SSH key"
  roles:
          #- role: '/home/menek/.ansible/TESTS/roles/create_user/'
    - roles/create_user
    - roles/test_bootstrap
