- name: Create a remote sudo user ["{{ user }}"] for CentOS 
  ansible.builtin.user:
    name: "{{ user }}"
    #password: "{{ user_password }}"
    shell: /bin/bash
    #uid: 1000
    groups:
      - wheel
    state: present
    createhome: yes
    home: /home/{{ user }}
    #    when: inventory_hostname in groups['kub-servers']['kub-master']

- name: Add a line to a file if the file does not exist, without passing regexp
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/{{ user }}
    line: '"{{ user }}" ALL=(ALL) NOPASSWD:ALL'
    create: yes
