- name: Create a remote sudo user for Ubuntu
  ansible.builtin.user:
    name: "{{ user }}"
    comment: "{{ password }}"
    uid: 1077
    groups:
      - sudo
    createhome: yes
    home: /home/{{ user }}
    state: present
