- name: Create a remote sudo user ["{{ user }}"] for Ubuntu
  ansible.builtin.user:
    name: "{{ user }}"
    comment: "{{ password }}"
    shell: /bin/bash
    #uid: 1000
    groups:
      - sudo
    createhome: yes
    home: /home/{{ user }}
    state: present
