- name: Create a ssh key pair
  import_tasks: generate_ssh_key.yml
  #when: inventory_hostname in groups['jumpserver']
  tags:
    - generate_key

- name: Distribute public key
  import_tasks: distribute_ssh_key.yml
  #when: inventory_hostname in groups['jumpserver']
  tags:
    - distribute_key

- name: Create a remote sudo user for CentOS 
  import_tasks: create_centos_user.yml
  #when: ansible_facts['os_family']|lower == 'centos'
  when: ansible_facts['distribution'] == "CentOS"
  tags:
    - create_sudo_user


- name: Create a remote sudo user for Ubuntu
  import_tasks: create_ubuntu_user.yml
  #when:  ansible_facts['os_family']|lower == 'ubuntu'
  when: ansible_facts['distribution'] == "Ubuntu"
  tags:
    - create_sudo_user

